apps/user/urls.py
# django
from django.urls import path, include
# third
# own
from apps.user.views import Logout

urlpatterns = [
    path('admin_bank/', include(('apps.user.urls_admin', 'admin'))),
    path('client/', include(('apps.user.urls_client', 'client'))),
    path('logout/', Logout.as_view(), name='logout'),
]

dj_bank/urls.py
# django
from django.contrib import admin
from django.urls import path, include
# third
# own
from apps.user.views import Login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name='login'),
    path('user/', include(('apps.user.urls', 'user')))
]

apps/base/models.py
from django.db import models

# Create your models here.

apps/user/models.py
# django
from django.db import models
from django.contrib.auth.models import User
# third
# own

# Create your models here.

class Ciudad(models.Model):
    codigo_ciudad = models.CharField(max_length=10, primary_key=True)
    nombre_ciudad = models.CharField(max_length=25)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):        #__unicode__
        return self.nombre_ciudad

    class Meta:
        verbose_name_plural = "Ciudades"
        verbose_name = "Ciudad"

ROL_CHOICES = (
    ('AMD', u'Administrador'),
    ('CLI', u'Cliente')
)

class Cliente(models.Model):
    cedula = models.CharField(max_length=12, primary_key=True)
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    telefono = models.CharField(max_length=15)
    direccion = models.CharField(max_length=50)
    codigo_ciudad = models.ForeignKey(Ciudad, max_length=10, on_delete=models.CASCADE)
    usuid = models.OneToOneField(User, on_delete=models.CASCADE)
    rol = models.CharField(max_length=20, choices=ROL_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Clientes"
        verbose_name = "Cliente"

ESTADO = (
    ('ACT', u'Activada'),
    ('DES', u'Desativada')
)

NOMBRE_CUENTA = (
    ('COR', u'Corriente'),
    ('AHO', u'Ahorro')
)

class Cuenta(models.Model):
    codigo_cuenta = models.CharField(max_length=10, primary_key=True)
    nombre_cuenta = models.CharField(max_length=25, choices=NOMBRE_CUENTA)
    estado = models.CharField(max_length=15, choices=ESTADO)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    saldo = models.FloatField(default=15000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre_cuenta

    class Meta:
        verbose_name_plural = "Cuentas"
        verbose_name = "Cuenta"

TIPO_MOVIMIENTO = (
    ('RET', u'Retiro'),
    ('DEP', u'Deposito')
)

class Movimiento(models.Model):
    id_movimiento = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    codigo_cuenta = models.ForeignKey(Cuenta, max_length=10, on_delete=models.CASCADE)
    fecha = models.DateField()
    tipo = models.CharField(max_length=15, choices=TIPO_MOVIMIENTO)
    saldo = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.tipo

    class Meta:
        verbose_name_plural = "Movimientos"
        verbose_name = "Movimiento"

apps/user/forms.py
# django
from django import forms
from django.utils.translation import gettext_lazy as _
# third
# own
from apps.user.models import Cliente, Ciudad, Cuenta, Movimiento, ROL_CHOICES

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = "__all__"
        labels = {
            'cedula': _(u'Número de Identificacion:'),
            'nombre': _(u'Nombre:'),
            'apellido': _(u'Apellido:'),
            'telefono': _(u'Telefono:'),
            'direccion': _(u'Direccion:'),
            'codigo_ciudad': _(u'Codigo Ciudad:'),
            'usuid': _(u'Username:'),
            'rol': _(u'Tipo de usuario')
        }

    def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

class CuentaForm(forms.ModelForm):
    class Meta:
        model = Cuenta
        fields = "__all__"
        labels = {
            'codigo_cuenta': _(u'Codigo Cuenta:'),
            'nombre_cuenta': _(u'Nombre Cuenta:'),
            'estado': _(u'Estado:'),
            'cliente': _(u'user:client:'),
            'saldo': _(u'Saldo')
        }

    def __init__(self, *args, **kwargs):
        super(CuentaForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

class MovimientoForm(forms.ModelForm):
    class Meta:
        model = Movimiento
        fields = "__all__"
        labels = {
            'id_movimiento': _(u'Codigo Movimiento:'),
            'cedula': _(u'Cedula:'),
            'codigo_cuenta': _(u'Codigo Cuenta:'),
            'fecha': _(u'Fecha Movimiento:'),
            'tipo': _(u'Tipo Movimientos:'),
            'saldo': _(u'Saldo Cuenta:')
        }

    def __init__(self, *args, **kwargs):
        super(MovimientoForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

class AdicionarClienteForm(forms.Form):
    username = forms.CharField(max_length=150, label='Username')
    email = forms.EmailField(max_length=150, label='Email')
    password = forms.CharField(max_length=128, label='Contraseña', widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length=128, label='Confirmar Contraseña', widget=forms.PasswordInput())
    cedula = forms.CharField(max_length=12, label='Cedula')
    nombre = forms.CharField(max_length=30, label='Nombre')
    apellido = forms.CharField(max_length=30, label='Apellido')
    telefono = forms.CharField(max_length=15, label='Telefono')
    direccion = forms.CharField(max_length=50, label='Direccion')
    nombre_ciudad = forms.ModelChoiceField(queryset=Ciudad.objects.all(), label='Ciudad')
    rol = forms.ChoiceField(choices=ROL_CHOICES, label='Tipo de Ususario', widget=forms.Select())

apps/base/views.py
from django.shortcuts import render

# Create your views here.

apps/user/views.py
# django
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.urls import reverse
# third
# own
from apps.user.models import Cliente

# Create your views here.

class Login(View):
    template_name = 'login.html'
    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        username = request.POST.get("signin_username")
        password = request.POST.get("signin_password")
        usuario = auth.authenticate(username=username, password=password)

        if usuario != None and usuario.is_active:
            auth.login(request, usuario)
            cliente = Cliente.objects.filter(usuid=usuario.pk)

            if cliente[0].rol == "CLI":
                return HttpResponseRedirect(reverse('user:client:perfil_cliente'))

            elif cliente[0].rol == "AMD":
                return HttpResponseRedirect(reverse('user:admin:perfil_administrador'))

            else:
                messages.add_message(request, messages.ERROR, "Rol de usuario inexistente")

        else:
            if usuario == None:
                messages.add_message(request, messages.ERROR, "El Usuario no existe en el Sistema")

            else:
                messages.add_message(request, messages.ERROR, "El Usuario esta inactivo")

        return render(request, self.template_name)

class Logout(View):

    def get(self, request):
        auth.logout(request)
        return HttpResponseRedirect(reverse('login'))

apps/base/templates/page_404.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Error</title>
    </head>
    <style>
        @import url(style.css);
    </style>
    <body>
        <h1>Error 404</h1>
    </body>
</html>

apps/user/templates/client/alerts.html
{%  load static %}
<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/sweetalert.css' %}">
<script src="{% static 'javascripts/jquery.js' %}"></script>
<script src="{% static 'javascripts/sweetalert.min.js' %}"></script>

<div id="alerts">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "error",
                            title: "ERROR",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>

            {% else %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "success",
                            title: "INFORMACIÓN",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

apps/user/templates/client/base_cliente.html
{% load static %}

<!DOCTYPE html>
    <!--[if IE 8]>         <html class="ie8"> <![endif]-->
    <!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
    <!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Banco</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <!-- Open Sans font from Google CDN -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
        <!-- Pixel Admin's stylesheets -->
        <link href="{% static 'stylesheets/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pixel-admin.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/widgets.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pages.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/rtl.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/themes.min.css' %}" rel="stylesheet" type="text/css">

        {% block styles %}
        {% endblock %}

        <!--[if lt IE 9]>
            <script src="{% static 'javascripts/ie.min.js' %}"></script>
        <![endif]-->
    </head>

    <body class="theme-adminflare main-menu-animated">
        <div id="main-wrapper">
            <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
                <!-- Main menu toggle -->
                <button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>

                <div class="navbar-inner">
                    <!-- Main navbar header -->
                    <div class="navbar-header">

                        <!-- Logo -->
                        <a href="" class="navbar-brand">
                            <div><img alt="Pixel Admin" src="{% static 'images/pixel-admin/main-navbar-logo.png' %}"></div>
                            Cliente
                        </a>

                        <!-- Main navbar toggle -->
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

                    </div> <!-- / .navbar-header -->

                    <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
                        <div>
                            <div class="right clearfix">
                                <ul class="nav navbar-nav pull-right right-navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
                                            <span class="btn-label icon fa fa-user"></span>
                                            <span>{{ user.first_name }}&nbsp;{{ user.last_name }}</span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'user:client:perfil_cliente' %}">
                                                    <i class="dropdown-icon fa fa-user"></i>&nbsp;&nbsp;Perfil
                                                </a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="{% url 'user:logout' %}">
                                                    <i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Cerrar Sesión
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul> <!-- / .navbar-nav -->
                            </div> <!-- / .right -->
                        </div>
                    </div> <!-- / #main-navbar-collapse -->
                </div> <!-- / .navbar-inner -->
            </div> <!-- / #main-navbar -->
        <!-- /2. $END_MAIN_NAVIGATION -->
            <div id="main-menu" role="navigation">
                <div id="main-menu-inner">
                    <div class="menu-content top" id="menu-content-demo">
                        <div>
                            <div class="text-bg">
                                <span class="text-slim">Bienvenido,</span>
                                <br>
                                <br>
                                <span class="text-semibold">{{ user.first_name }}</span>
                            </div>
                            <img src="{% static 'images/usuario.jpg'%}" id="img_usuario" alt="Foto Usuario" style="background: white;">
                        </div>
                    </div>
                    <div>
                        <ul class="navigation">
                            <li>
                                <a href="{% url 'user:client:perfil_cliente' %}">
                                    <i class="menu-icon fa fa-user"></i>
                                    <span class="mm-text">Perfil</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'user:client:listar_cuentas' %}">
                                    <i class="menu-icon fa fa-eye"></i>
                                    <span class="mm-text">Cuentas</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'user:client:listar_movimientos' %}">
                                    <i class="menu-icon fa fa-eye"></i>
                                    <span class="mm-text">Movimientos</span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'user:logout' %}">
                                    <i class="menu-icon fa fa-power-off"></i>
                                    <span class="mm-text">Cerrar Sesion</span>
                                </a>
                            </li>
                        </ul> <!-- / .navigation -->
                    </div>
                </div> <!-- / #main-menu-inner -->
            </div> <!-- / #main-menu -->
        <!-- /4. $MAIN_MENU -->
            <div id="content-wrapper">

                {% block content %}
                {% endblock %}

            </div> <!-- / #content-wrapper -->
            <div id="main-menu-bg"></div>
        </div> <!-- / #main-wrapper -->
        <!-- Get jQuery from Google CDN -->
        <!--[if !IE]> -->
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js">'+"<"+"/script>"); </script>
        <!-- <![endif]-->
        <!--[if lte IE 9]>
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">'+"<"+"/script>"); </script>
        <![endif]-->
        <!-- Pixel Admin's javascripts -->
        <script src="{% static 'javascripts/bootstrap.min.js' %}"></script>
        <script src="{% static 'javascripts/pixel-admin.min.js' %}"></script>
        <script>var init = [];</script>
        <script type="text/javascript">
            init.push(function () {});
            window.PixelAdmin.start(init);
        </script>
        {% block scripts %}
        {% endblock %}

    </body>
</html>

apps/user/templates/client/form_cuenta.html
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        <label for="jq-validation-url" class="col-sm-3 control-label">
            <strong>{{ field.label }}</strong>
        </label>
        <div class="col-sm-9">
            {{ field }}
        </div>
    </div>
{% endfor %}

apps/user/templates/client/form_movimiento.html
{% for field in form %}
    <div class="form-group">
        {{ field.errors }}
        <label for="jq-validation-url" class="col-sm-3 control-label">
            <strong>{{ field.label }}</strong>
        </label>
        <div class="col-sm-9">
            {{ field }}
        </div>
    </div>
{% endfor %}

apps/user/templates/client/listar_cuentas.html
{% extends 'client/base_cliente.html' %}

{% block styles %}
{% endblock %}

{% block content %}
    {% include 'client/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <!-- Page header, center on small screens -->
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>&nbsp;&nbsp;Cuentas
            </h1>
            <div class="col-xs-12 col-sm-8">
                <div class="row">
                    <hr class="visible-xs no-grid-gutter-h">
                    <!-- "Create project" button, width=auto on desktops -->
                    <div class="pull-right col-xs-12 col-sm-auto">
                        <a href="{% url 'user:client:listar_cuentas_reporte' %}">
                            <button class="btn  btn-labeled btn-primary" >
                                <span class="btn-label icon fa fa-print"></span>
                                Generar Reporte
                            </button>&nbsp;&nbsp;
                        </a>
                    </div>
                    <!-- Margin -->
                    <div class="visible-xs clearfix form-group-margin"></div>
                    <!-- Search field -->
                </div>
            </div>
        </div>
    </div> <!-- / .page-header -->
    <!-- / Javascript -->
    <div class="panel">
        {% csrf_token %}
        <div class="panel-body">
            <div class="table-primary">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables-example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Codigo Cuenta</th>
                            <th>Nombre Cuenta</th>
                            <th>Estado</th>
                            <th>Cliente</th>
                            <th>Saldo</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for cuenta in cuentas %}
                            <tr class="odd gradeX">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ cuenta.codigo_cuenta }}</td>
                                <td>{{ cuenta.nombre_cuenta }}</td>
                                <td>{{ cuenta.estado }}</td>
                                <td>{{ cuenta.cliente }}</td>
                                <td>{{ cuenta.saldo }}</td>
                                <td>
                                    <a href="{% url 'user:client:visualizar_cuenta' cuenta.pk %}">
                                        <button class="btn  btn-labeled btn-primary" >
                                           <span class="btn-label icon fa fa-eye"></span>
                                            Visualizar
                                        </button>&nbsp;&nbsp;
                                     </a>
                                    <a href="{% url 'user:client:realizar_deposito' cuenta.pk %}">
                                        <button class="btn  btn-labeled btn-primary" >
                                            <span class="btn-label icon fa fa-money"></span>
                                            Depositar
                                        </button>&nbsp;&nbsp;
                                     </a>
                                    <a href="{% url 'user:client:realizar_retiro' cuenta.pk %}">
                                        <button class="btn  btn-labeled btn-primary" >
                                            <span class="btn-label icon fa fa-money"></span>
                                            Retirar
                                        </button>&nbsp;&nbsp;
                                     </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        init.push(function ()
        {
            $('#jq-datatables-example').dataTable();
            $('#jq-datatables-example_wrapper .table-caption').text('Listado de Cuentas');
            $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Buscar...');
        });
    </script>
{% endblock %}

apps/user/templates/client/listar_cuentas_reporte.html
{% extends 'client/base_cliente.html' %}

{% block styles %}
{% endblock %}

{% block content %}
    {% include 'client/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <!-- Page header, center on small screens -->
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>&nbsp;&nbsp;Cuentas
            </h1>
            <div class="col-xs-12 col-sm-8">
                <div class="row">
                    <hr class="visible-xs no-grid-gutter-h">
                    <!-- "Create project" button, width=auto on desktops -->
                    <!-- Margin -->
                    <div class="visible-xs clearfix form-group-margin"></div>
                    <!-- Search field -->
                </div>
            </div>
        </div>
    </div> <!-- / .page-header -->
    <!-- / Javascript -->
    <div class="panel">
        {% csrf_token %}
        <div class="panel-body">
            <div class="table-primary">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables-example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Codigo Cuenta</th>
                            <th>Nombre Cuenta</th>
                            <th>Estado</th>
                            <th>Cliente</th>
                            <th>Saldo</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for cuenta in cuentas %}
                            <tr class="odd gradeX">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ cuenta.codigo_cuenta }}</td>
                                <td>{{ cuenta.nombre_cuenta }}</td>
                                <td>{{ cuenta.estado }}</td>
                                <td>{{ cuenta.cliente }}</td>
                                <td>{{ cuenta.saldo }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        init.push(function ()
        {
            $('#jq-datatables-example').dataTable();
            $('#jq-datatables-example_wrapper .table-caption').text('Listado de Cuentas');
            $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Buscar...');
        });
    </script>
{% endblock %}

apps/user/templates/client/listar_movimientos_by_fecha.html
{% extends 'client/base_cliente.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    {% include 'client/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>
                &nbsp;&nbsp;Generar Reporte By Fecha
            </h1>
        </div>
    </div>
    <div class="panel" style="border-radius: 10px 10px 10px 10px; width: 250px; height: 340px">{% csrf_token %}
        <form method="post" id="form_usuario" enctype="multipart/form-data" style="position: center;">{% csrf_token %}
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Generar Reporte By Fecha
            <br />
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fecha Inicio
            <br />
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="date" name="fecha_inicio" required style="border-radius: 10px 10px 10px 10px"/>
            <br />
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fecha Fin
            <br />
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="date" name="fecha_fin" required style="border-radius: 10px 10px 10px 10px"/>
            <br />
            <br />
            <div class="form-group">
                <a href="listar_movimientos_por_fecha.html">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-primary">
                        <span class="btn-label icon fa fa-print"></span>
                        Generar Reporte
                    </button>
                </a>
            </div>
        </form>
        <a href="{% url 'user:client:listar_movimientos' %}">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button class="btn  btn-labeled btn-primary">
                <span class="btn-label icon fa fa-arrow-left"></span>
                Salir
            </button>
        </a>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            $('body').addClass("page-profile");
            $('#item_usuario').addClass("active");
        });

        window.PixelAdmin.start(init);
    </script>

    {% block scripts_crud %}
    {% endblock %}
{% endblock %}

apps/user/templates/client/perfil_cliente.html
{% extends 'client/base_cliente.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    {% include 'client/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>
                &nbsp;&nbsp;Perfil Cliente
            </h1>
        </div>
    </div>
    <div class="profile-full-name">
        <span class="text-semibold">
            <i class="fa fa-edit page-header-icon"></i>
            Datos Cliente
        </span>
    </div>

    <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
                <div class="panel">
                    <br><br>
                    <form method="post" id="form_usuario" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.errors }}
                                <label for="jq-validation-url" class="col-sm-3 control-label">
                                    <strong>{{ field.label }}</strong>
                                </label>
                                <div class="col-sm-9">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <br>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <a href="{% url 'user:client:perfil_cliente' %}">
                                    <button type="submit" class="btn btn-primary">
                                        <span class="btn-label icon fa fa-pencil"></span>
                                        Modificar
                                    </button>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            $('body').addClass("page-profile");
            $('#item_usuario').addClass("active");
        });

        window.PixelAdmin.start(init);
    </script>

    {% block scripts_crud %}
        <script>
            $('#id_rol').attr('style', 'pointer-events: none;');
            $('#id_usuid').attr('style', 'pointer-events: none;');
            $('#id_cedula').prop('readonly',true);
        </script>
    {% endblock %}
{% endblock %}